# syntax=docker/dockerfile:1
FROM php:7.4-apache
COPY php/ /var/www/html
WORKDIR /var/www/html


ARG DEBIAN_FRONTEND=newt

RUN apt-get -y update && apt-get install -y \
apache2 \
php7.4 \
libapache2-mod-php7.4 \
php7.4-bcmath \
php7.4-gd \
php7.4-json \
php7.4-sqlite \
php7.4-mysql \
php7.4-curl \
php7.4-xml \
php7.4-mbstring \
php7.4-zip \
mcrypt \
nano

RUN apt-get install locales
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf

RUN chgrp -R www-data /var/www
RUN find /var/www -type d -exec chmod 775 {} +
RUN find /var/www -type f -exec chmod 664 {} +

EXPOSE 80

CMD ["/usr/sbin/apache2ctl","-DFOREGROUND"]