# syntax=docker/dockerfile:1
FROM php:7.4-apache
COPY php/ /var/www/html
WORKDIR /var/www/html

RUN apt-get update -y && \
	apt-get install -y \
		libfreetype6-dev \
		libjpeg62-turbo-dev \
		libpng-dev \ 
		mcrypt \
		curl

RUN apt-get install locales -y
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf

RUN chgrp -R www-data /var/www
RUN find /var/www -type d -exec chmod 775 {} +
RUN find /var/www -type f -exec chmod 664 {} +

EXPOSE 80